# 示例智能体配置
id: "sample-agent-001"
name: "示例智能体"
description: "一个用于展示Mantras-Next功能的示例智能体"
metadata:
  version: "1.0.0"
  author: "Mantras Team"
  tags:
    - "sample"
    - "demo"
    - "ide"

# 最大迭代次数
maxIterations: 10

# 停止条件
stopCriteria:
  stopWords:
    - "完成"
    - "结束"
    - "成功"

# 工具配置
tools:
  - id: "code-formatter"
    name: "代码格式化工具"
    description: "格式化代码，使其符合指定的风格规范"
    category: "code"
    requiredPermissions:
      - "read_file"
    metadata:
      version: "1.0.0"
      supportedLanguages:
        - "typescript"
        - "javascript"
        - "json"

  - id: "file-reader"
    name: "文件读取工具"
    description: "读取文件内容，支持部分读取和行号显示"
    category: "file"
    requiredPermissions:
      - "read_file"
    metadata:
      version: "1.0.0"
      supportedFileTypes:
        - "txt"
        - "md"
        - "js"
        - "ts"
        - "json"

# 记忆配置
memory:
  id: "simple-memory-001"
  name: "简单记忆系统"
  description: "一个基本的记忆实现，使用Map存储数据"
  maxSize: 100
  ttl: 3600000  # 1小时，单位：毫秒