# /Users/bytedance/Desktop/trae/mantras/config/agents/sample-agent.yaml
id: "agent-001"
name: "Sample Assistant Agent"
status: "idle"
capabilities:
  - "code-generation"
  - "file-manipulation"
  - "information-retrieval"
items:
  - id: "item-001-greet"
    name: "Greeter Tool"
    description: "A simple tool to greet the user."
    executionPath: "config/agents/tools/greeting-tool.ts" # Path relative to project root
    metadata:
      version: "1.0.0"
      tags: ["greeting", "utility"]
  - id: "item-002-file-reader"
    name: "File Reader Tool"
    description: "Reads content from a specified file."
    # executionPath: "./tools/file-reader-tool.ts" # Intentionally commented out to show handling
    metadata:
      version: "0.9.0"
      supportedFileTypes: ["txt", "md", "js", "ts"]
      requiresPermission: "readFile"
  - id: "item-003-code-formatter"
    name: "Code Formatter Tool"
    description: "Formats code according to predefined styles."
    executionPath: "src/tools/code-formatter.tool.ts" # Path relative to project root
    metadata:
      version: "1.2.0"
      supportedLanguages: ["javascript", "typescript", "python"]
      styleGuides: ["prettier", "eslint"]